table _Measures
	lineageTag: d7bb6eed-0d84-4e40-9f4a-da9651162138

	measure 'Delivery Net Value' = sum(FACT_SALES_PERFORMANCE[DELIVERY_NET_VALUE_GC])
		formatString: #,0.00
		lineageTag: 11934b38-19fd-423b-87f9-2c30878b65eb

	measure 'Delivery Quantity' = Sum(FACT_SALES_PERFORMANCE[DELIVERY_QUANTITY])
		formatString: #,0
		lineageTag: 6b1c9184-f74a-443c-b2fc-1c4d148e1123

	measure 'Net Value' = sum(FACT_SALES_PERFORMANCE[INVOICE_NET_VALUE_GC])
		formatString: #,0.00
		lineageTag: dd4e8d08-a329-40e1-b08e-8c970037b562

	measure 'Sales Quantity' = sum(FACT_SALES_PERFORMANCE[INVOICE_QUANTITY])
		formatString: #,0.00
		lineageTag: 4c721c6b-8481-46c0-97dc-e03323ca1a77

	measure ShowTable = ```
			
			IF(SELECTEDVALUE('Reports'[Reports]) = "None", 0, 1)
			
			```
		formatString: 0
		lineageTag: 6bd90952-491e-437a-89d0-3c5cf34aa2b1

	measure 'Confirmed Orders' = calculate(sum(FACT_SALES_OPEN_ORDERS[OPEN_NETVALUE_GC]), FACT_SALES_OPEN_ORDERS[FLAG_CONFIRMED_QTY]=1)
		formatString: #,0
		lineageTag: ba02bc4e-128d-452b-a2ea-7bf1d8502a81

	measure 'Unconfirmed Orders' = calculate(sum(FACT_SALES_OPEN_ORDERS[OPEN_NETVALUE_GC]), FACT_SALES_OPEN_ORDERS[FLAG_CONFIRMED_QTY]=0)
		formatString: #,0
		lineageTag: ded5b3bf-07e4-4dd6-9549-15e5069568cc

	measure 'MTD BUD vs. ACT in k€' = (sum(FACT_SALES_PERFORMANCE[INVOICE_NET_VALUE_GC])-sum(PBI_V_BUDGET[REVENUE_EUR]))/1000
		formatString: #,0
		lineageTag: 0c4c437a-5a43-488b-a4ff-8b026b759ee4

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'BUD vs ACT in %' = ```
			DIVIDE(
			    SUM(FACT_SALES_PERFORMANCE[INVOICE_NET_VALUE_GC]),
			    SUM(PBI_V_BUDGET[REVENUE_EUR]),
			    BLANK()
			)
			
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 390cf592-0b82-4370-9b6b-c0fbe5ab825f

	measure INVOICE_YTD = ```
			
			(TOTALYTD(
			    SUM(FACT_SALES_PERFORMANCE[INVOICE_NET_VALUE_GC]),
			    Datumstabelle[Date]  -- Bezug auf deine Datumstabelle
			))/1000
			
			```
		formatString: #,0
		lineageTag: d227f598-ee0c-41b1-9866-cfd4d67c9643

		annotation PBI_FormatHint = {"isDecimal":true}

	measure BUDGET_YTD = ```
			
			(TOTALYTD(
			    SUM(PBI_V_BUDGET[REVENUE_EUR]),
			    Datumstabelle[Date]  -- Bezug auf deine Datumstabelle
			))/1000
			
			```
		formatString: #,0
		lineageTag: 7089ab9b-d7a6-4669-875d-05ce29070187

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'BUD vs ACT YTD in %' = ```
			DIVIDE(
			    [INVOICE_YTD],
			    [BUDGET_YTD],
			    BLANK()
			)
			
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: d0da47a9-68a4-44f1-92e2-2e2e692f0bfa

	measure 'BUD vs ACT YTD' = [INVOICE_YTD]-[BUDGET_YTD]
		formatString: #,0
		lineageTag: 9d6d7a41-4e4a-4229-a38f-af71e293e6f6

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'MTD BUD in k€' = sum(PBI_V_BUDGET[REVENUE_EUR])/1000
		formatString: #,0
		lineageTag: de91df97-ddde-45d6-a96d-58ff766416f5

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'MTD ACT in k€' = sum(FACT_SALES_PERFORMANCE[INVOICE_NET_VALUE_GC])/1000
		formatString: #,0
		lineageTag: 344018cf-d9c3-4a82-8c24-db7ade3d8ad5

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Actual Budget comparison %' = ```
			
			var up_arrow = "+"
			var down_arrow = "-"
			var thisyear = [Net Value]
			var LY = [Budget revenues]
			var difpercentage = DIVIDE(thisyear,LY)-1
			
			Return
			IF(
			    difpercentage < 0, 
			      FORMAT(difpercentage, "0%") ,
			    up_arrow & FORMAT(difpercentage, "0%")
			)
			```
		displayFolder: Testordner
		lineageTag: b7c300df-401c-49bb-998d-0ee1da3e6683

	measure 'Budget revenues' = SUM(PBI_V_BUDGET[REVENUE_EUR])
		lineageTag: f77b0e46-75ee-4f9d-bc0b-fc1b214907f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Value Invoices PY' = CALCULATE([Net Value], SAMEPERIODLASTYEAR(Datumstabelle[Date].[Date]))
		lineageTag: 2edb4dd2-9bcf-453e-943d-27996786f806

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Actual PY comparison %' = ```
			
			var up_arrow = "+"
			var down_arrow = "-"
			var thisyear = [Net Value]
			var LY = [Net Value Invoices PY]
			var difpercentage = DIVIDE(thisyear,LY)-1
			
			Return
			IF(
			    difpercentage < 0, 
			      FORMAT(difpercentage, "0%") ,
			    up_arrow & FORMAT(difpercentage, "0%")
			)
			```
		displayFolder: Testordner
		lineageTag: 5bacd3ce-5525-4213-8038-3fbae0de17ab

	measure 'Budget YTD (bis Heute)' = ```
			
			CALCULATE(
			    SUM(PBI_V_BUDGET[REVENUE_EUR]),
			    DATESYTD(
			        Datumstabelle[Date].[Date],
			        "31.12"  -- oder anderes Geschäftsjahresende
			    ),
			    FILTER(
			        Datumstabelle,
			        Datumstabelle[Date].[Date] <= TODAY()
			    )
			)
			
			```
		lineageTag: 5715e642-b566-4339-899b-1e27ab41757e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Actual Budget comparison % YTD' = ```
			
			var up_arrow = "+"
			var down_arrow = "-"
			var thisyear = [Net Value]
			var LY = [Budget YTD (bis Heute)]
			var difpercentage = DIVIDE(thisyear,LY)-1
			
			Return
			IF(
			    difpercentage < 0, 
			      FORMAT(difpercentage, "0%") ,
			    up_arrow & FORMAT(difpercentage, "0%")
			)
			```
		displayFolder: Testordner
		lineageTag: d7258316-7d01-4813-9fcf-0e118e35e7eb

	measure 'Actuals vs Budget YTD' = ([Net Value]/[Budget YTD (bis Heute)])
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: c6ad2bde-ac68-4783-b19e-a56e4fbe4fa9

	measure HasHistoricalData = ```
			
			VAR CurrentMonth = MAX(Datumstabelle[Date].[Monat])
			VAR Kunde = SELECTEDVALUE(DIM_DEBITOR_GEN[DEBITOR_GROUP_NAME])
			VAR Standort = SELECTEDVALUE('Legal Entity Table'[LE])
			
			RETURN
			CALCULATE(
			    COUNTROWS('DeineTabelle'),
			    'DeineTabelle'[Kunde] = Kunde,
			    'DeineTabelle'[Standort] = Standort,
			    'DeineTabelle'[Monat] < CurrentMonth,
			    (
			        'DeineTabelle'[Deliveries] > 0 
			        || 'DeineTabelle'[Confirmed Orders] > 0 
			        || 'DeineTabelle'[Unconfirmed Orders] > 0
			    )
			)
			
			```
		lineageTag: 6bcae7c6-5ba5-4cc6-895d-c561ab1fd1ac

	measure 'Net Value Invoices 2022' = ```
			
			CALCULATE(
			    [Net Value],
			    REMOVEFILTERS('Datumstabelle'),
			    'Datumstabelle'[Jahr] = 2022
			)
			
			```
		lineageTag: ca33a151-bd02-4f08-ad1b-ff9e46c3cd89

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Value Invoices 2024' = ```
			
			CALCULATE(
			    [Net Value],
			    REMOVEFILTERS('Datumstabelle'),
			    'Datumstabelle'[Jahr] = 2024
			)
			
			```
		lineageTag: 5ee63ccb-b6c9-448b-b956-29e20d22fcd8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Value Invoices 2023' = ```
			
			CALCULATE(
			    [Net Value],
			    REMOVEFILTERS('Datumstabelle'),
			    'Datumstabelle'[Jahr] = 2023
			)
			
			```
		lineageTag: c83a39a7-f446-4a25-bd15-169e33601f76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Value Invoices 2025' = ```
			
			CALCULATE(
			    [Net Value],
			    REMOVEFILTERS('Datumstabelle'),
			    'Datumstabelle'[Jahr] = 2025
			)
			
			```
		lineageTag: 62215ba7-801a-4709-baaf-e925a7d4cacb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Value Invoices 2026' = ```
			
			CALCULATE(
			    [Net Value],
			    REMOVEFILTERS('Datumstabelle'),
			    'Datumstabelle'[Jahr] = 2026
			)
			
			```
		lineageTag: 72f2099e-cd36-423e-adc0-633ec27dc114

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Budget 2024' = ```
			
			CALCULATE(
			    [Budget revenues],
			    REMOVEFILTERS('Datumstabelle'),
			    'Datumstabelle'[Jahr] = 2024
			)
			
			```
		lineageTag: b69c2aeb-b51d-4dce-a0ce-fd939f43131c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Budget 2025' = ```
			
			CALCULATE(
			    [Budget revenues],
			    REMOVEFILTERS('Datumstabelle'),
			    'Datumstabelle'[Jahr] = 2025
			)
			
			```
		lineageTag: db7ef145-1e6e-4394-87bd-850b5d26d10d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Invoices 2022' = ```
			
			CALCULATE(
			    [Sales Quantity],
			    REMOVEFILTERS('Datumstabelle'),
			    'Datumstabelle'[Jahr] = 2022
			)
			
			```
		lineageTag: f91d4d29-7f23-454b-9a7f-65ab425ffbdc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Invoices 2023' = ```
			
			CALCULATE(
			    [Sales Quantity],
			    REMOVEFILTERS('Datumstabelle'),
			    'Datumstabelle'[Jahr] = 2023
			)
			
			```
		lineageTag: 681fd450-4bdf-48ce-819e-377d86be697a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Invoices 2024' = ```
			
			CALCULATE(
			    [Sales Quantity],
			    REMOVEFILTERS('Datumstabelle'),
			    'Datumstabelle'[Jahr] = 2024
			)
			
			```
		lineageTag: 5a15272b-7891-4a74-8309-099911d28fc8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Invoices 2025' = ```
			
			CALCULATE(
			    [Sales Quantity],
			    REMOVEFILTERS('Datumstabelle'),
			    'Datumstabelle'[Jahr] = 2025
			)
			
			```
		lineageTag: 1fe7f428-8cc2-41f0-96ad-376380b54e2c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Invoices 2026' = ```
			
			CALCULATE(
			    [Sales Quantity],
			    REMOVEFILTERS('Datumstabelle'),
			    'Datumstabelle'[Jahr] = 2026
			)
			
			```
		lineageTag: 73d996b8-e396-477d-952c-4fe21a7b322d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ShowCustomerMeasure = ```
			
			IF(
			    CALCULATE(SUM(FACT_SALES_OPEN_ORDERS[OPEN_NETVALUE_GC]), FACT_SALES_OPEN_ORDERS[FLAG_CONFIRMED_QTY]=1) > 0 ||
			    CALCULATE(SUM(FACT_SALES_OPEN_ORDERS[OPEN_NETVALUE_GC]), FACT_SALES_OPEN_ORDERS[FLAG_CONFIRMED_QTY]=0) > 0 ||
			    SUM(FACT_SALES_PERFORMANCE[DELIVERY_NET_VALUE_GC]) > 0,
			    1, 
			    0
			)
			
			```
		formatString: 0
		lineageTag: edbae64d-f2a6-4566-9f88-a2c3ef3ed3bd

	measure 'Actuals vs Budget' = ([Net Value]/[Budget revenues])
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Testordner
		lineageTag: 4288374d-44fa-4363-827b-cc8594f713a9

	measure Blank = BLANK()
		formatString: 0
		lineageTag: f300f233-02e6-4132-8aaa-80324b10b292

	measure 'Total Price Today' = ```
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            'FACT PRICING MONITOR',
			            'FACT PRICING MONITOR'[VALID_FROM] <= TODAY() && 'FACT PRICING MONITOR'[VALID_TO] >= TODAY()
			        ),
			        'FACT PRICING MONITOR'[SCALE_PRICE] * [Sum planned quantity]
			    )
			)
			
			```
		lineageTag: f41cc2e4-191e-4a82-bbb4-1a9bde506a11

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum planned quantity' = sum('ERP-FC'[PLANNED_QUANTITY])
		lineageTag: f4280374-2147-415e-b96d-1e4d0ecb982d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Price Today new' = ```
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            'FACT PRICING MONITOR',
			            'FACT PRICING MONITOR'[VALID_FROM] <= TODAY() &&
			            'FACT PRICING MONITOR'[VALID_TO] >= TODAY() &&
			            [Sum planned quantity] >= 'FACT PRICING MONITOR'[SCALE_PRICE_UNIT_FROM] &&
			            [Sum planned quantity] <= 'FACT PRICING MONITOR'[SCALE_PRICE_UNIT_TO]
			        ),
			        'FACT PRICING MONITOR'[Scale Price adjusted] * [Sum planned quantity]
			    )
			)
			
			```
		lineageTag: 057ba042-1525-48a1-8aa6-5e92777c5cee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Price today 2' = [Total Price Today new]/('FACT PRICING MONITOR'[UNIT_PRICE])
		lineageTag: 8722d445-a3fa-4b69-88e1-197f4ad2622f

	measure 'Net Value comparison PY' = [Net Value]-[Net Value Invoices PY]
		lineageTag: dfb1a329-e227-4fe3-b95c-0525f2f62ff9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Value comparison % PY' = ([Net Value]/[Net Value Invoices PY])-1
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7697b927-f1f1-4cc1-9acb-f9c0b35becf5

	measure 'Net Value Vergleich Pfeil' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR thisyear = [Net Value]
			VAR LY = [Net Value Invoices PY]
			VAR difpercentage = DIVIDE(thisyear, LY) - 1
			VAR rounded_dif = ROUND(difpercentage * 100, 0) // Rundet die Differenz auf ganze Zahlen
			
			-- Dynamische Formatierung für LY
			VAR LY_formatted = 
			    IF(LY >= 1000000, 
			        FORMAT(LY / 1000000, "0.0") & " Mio.", 
			        IF(LY >= 1000, 
			            FORMAT(LY / 1000, "0") & " Tsd.", 
			            FORMAT(LY, "#,0")
			        )
			    )
			
			RETURN
			IF(
			    difpercentage < 0, 
			    down_arrow & FORMAT(rounded_dif, "0") & "% | PY " & LY_formatted, 
			    up_arrow & FORMAT(rounded_dif, "0") & "% | PY " & LY_formatted
			)
			
			```
		lineageTag: 84b81955-ace0-42e2-a8d9-9e1731063432

	measure 'Delivery Net Value Vergleich Pfeil' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR thisyear = [Delivery Net Value]
			VAR LY = [Delivery Net Value PY]
			VAR difpercentage = DIVIDE(thisyear, LY) - 1
			VAR rounded_dif = ROUND(difpercentage * 100, 0) // Rundet die Differenz auf ganze Zahlen
			
			-- Dynamische Formatierung für LY
			VAR LY_formatted = 
			    IF(LY >= 1000000, 
			        FORMAT(LY / 1000000, "0.0") & " Mio.", 
			        IF(LY >= 1000, 
			            FORMAT(LY / 1000, "0") & " Tsd.", 
			            FORMAT(LY, "#,0")
			        )
			    )
			
			RETURN
			IF(
			    difpercentage < 0, 
			    down_arrow & FORMAT(rounded_dif, "0") & "% | PY " & LY_formatted, 
			    up_arrow & FORMAT(rounded_dif, "0") & "% | PY " & LY_formatted
			)
			
			```
		lineageTag: 518c0feb-3f58-4be9-a13b-f6e43a550c9d

	measure 'Delivery Net Value PY' = CALCULATE([Delivery Net Value], SAMEPERIODLASTYEAR(Datumstabelle[Date].[Date]))
		lineageTag: 5a40b039-55f2-4ea0-9842-a95914b8d798

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'VMI-FC PY' = CALCULATE(sum('VMI-FC'[VMI-FC (EUR)]), SAMEPERIODLASTYEAR(Datumstabelle[Date].[Date]))
		lineageTag: 3a562ce9-54e7-4915-a475-252c0eaa67f8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'VMI FC Vergleich Pfeil' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR thisyear = sum('VMI-FC'[VMI-FC (EUR)])
			VAR LY = [VMI-FC PY]
			VAR difpercentage = DIVIDE(thisyear, LY) - 1
			VAR rounded_dif = ROUND(difpercentage * 100, 0) // Rundet die Differenz auf ganze Zahlen
			
			-- Dynamische Formatierung für LY
			VAR LY_formatted = 
			    IF(LY >= 1000000, 
			        FORMAT(LY / 1000000, "0.0") & " Mio.", 
			        IF(LY >= 1000, 
			            FORMAT(LY / 1000, "0") & " Tsd.", 
			            FORMAT(LY, "#,0")
			        )
			    )
			
			RETURN
			IF(
			    difpercentage < 0, 
			    down_arrow & FORMAT(rounded_dif, "0") & "% | PY " & LY_formatted, 
			    up_arrow & FORMAT(rounded_dif, "0") & "% | PY " & LY_formatted
			)
			
			```
		lineageTag: b4c91f06-c2f2-44eb-86c9-c52d44a39fde

	measure 'Confirmed Orders PY' = CALCULATE([Confirmed Orders], SAMEPERIODLASTYEAR(Datumstabelle[Date].[Date]))
		lineageTag: 338297f8-1d27-4a5e-8850-3017c5dc31dc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unconfirmed Orders PY' = CALCULATE([Unconfirmed Orders], SAMEPERIODLASTYEAR(Datumstabelle[Date].[Date]))
		lineageTag: eb063faf-d1a0-4c04-89ed-4c9fcb91d8d8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Uncofirmed Orders Vergleich Pfeil' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR thisyear = [Unconfirmed Orders]
			VAR LY = [Unconfirmed Orders PY]
			VAR difpercentage = DIVIDE(thisyear, LY) - 1
			VAR rounded_dif = ROUND(difpercentage * 100, 0) // Rundet die Differenz auf ganze Zahlen
			
			-- Dynamische Formatierung für LY
			VAR LY_formatted = 
			    IF(LY >= 1000000, 
			        FORMAT(LY / 1000000, "0.0") & " Mio.", 
			        IF(LY >= 1000, 
			            FORMAT(LY / 1000, "0") & " Tsd.", 
			            FORMAT(LY, "#,0")
			        )
			    )
			
			RETURN
			IF(
			    difpercentage < 0, 
			    down_arrow & FORMAT(rounded_dif, "0") & "% | PY " & LY_formatted, 
			    up_arrow & FORMAT(rounded_dif, "0") & "% | PY " & LY_formatted
			)
			
			```
		lineageTag: dcb29009-9e13-4bee-919e-21140fe87f3d

	measure 'Cofirmed Orders Vergleich Pfeil' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR thisyear = [Confirmed Orders]
			VAR LY = [Confirmed Orders PY]
			VAR difpercentage = DIVIDE(thisyear, LY) - 1
			VAR rounded_dif = ROUND(difpercentage * 100, 0) // Rundet die Differenz auf ganze Zahlen
			
			-- Dynamische Formatierung für LY
			VAR LY_formatted = 
			    IF(LY >= 1000000, 
			        FORMAT(LY / 1000000, "0.0") & " Mio.", 
			        IF(LY >= 1000, 
			            FORMAT(LY / 1000, "0") & " Tsd.", 
			            FORMAT(LY, "#,0")
			        )
			    )
			
			RETURN
			IF(
			    difpercentage < 0, 
			    down_arrow & FORMAT(rounded_dif, "0") & "% | PY " & LY_formatted, 
			    up_arrow & FORMAT(rounded_dif, "0") & "% | PY " & LY_formatted
			)
			
			```
		lineageTag: 5f7fc772-489f-4b8e-a82a-4004dd12e9b4

	measure 'Budget PY' = calculate([Budget revenues], SAMEPERIODLASTYEAR(Datumstabelle[Date].[Date]))
		lineageTag: fa5b8b99-17a0-493b-8353-1edbbb3e0bcd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Budget Vergleich Pfeil' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR thisyear = [Budget revenues]
			VAR LY = [Budget PY]
			VAR difpercentage = DIVIDE(thisyear, LY) - 1
			VAR rounded_dif = ROUND(difpercentage * 100, 0) // Rundet die Differenz auf ganze Zahlen
			
			-- Dynamische Formatierung für LY
			VAR LY_formatted = 
			    IF(LY >= 1000000, 
			        FORMAT(LY / 1000000, "0.0") & " Mio.", 
			        IF(LY >= 1000, 
			            FORMAT(LY / 1000, "0") & " Tsd.", 
			            FORMAT(LY, "#,0")
			        )
			    )
			
			RETURN
			IF(
			    difpercentage < 0, 
			    down_arrow & FORMAT(rounded_dif, "0") & "% | PY " & LY_formatted, 
			    up_arrow & FORMAT(rounded_dif, "0") & "% | PY " & LY_formatted
			)
			
			```
		lineageTag: 5d21c424-e31d-4c99-8f17-b126fd52fc2e

	measure 'Budget comparison % PY' = ([Budget revenues]/[Budget PY])-1
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 90df331c-0e89-4052-9d76-a497a28f72f3

	measure 'Budget vs Actuals %' = ([Budget revenues]/[Sum all])-1
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 86f3cfdf-428b-47a2-977b-9909923d5001

	measure 'Kumuliertes Budget' = ```
			
			CALCULATE(
			    [Budget revenues],
			    FILTER(
			        ALLSELECTED(Datumstabelle),
			        Datumstabelle[Date] <= MAX(Datumstabelle[Date])
			    )
			)
			
			```
		lineageTag: b332fdbf-8d1b-4a05-99b9-db2cb8b0064a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Kumulierter Net Value' = ```
			
			CALCULATE(
			    [Net Value],
			    FILTER(
			        ALLSELECTED(Datumstabelle),
			        Datumstabelle[Date] <= MAX(Datumstabelle[Date])
			    )
			)
			
			```
		lineageTag: 157b5ad8-0752-47a8-8d04-82cd910e9790

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Kumuliertes Delivery Net Value' = ```
			
			CALCULATE(
			    [Delivery Net Value],
			    FILTER(
			        ALLSELECTED(Datumstabelle),
			        Datumstabelle[Date] <= MAX(Datumstabelle[Date])
			    )
			)
			
			```
		lineageTag: ade34cb7-d8a8-4b4d-920d-0bdd0b05189e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Kumuliertes VMI-FC' = ```
			
			CALCULATE(
			    sum('VMI-FC'[VMI-FC (EUR)]),
			    FILTER(
			        ALLSELECTED(Datumstabelle),
			        Datumstabelle[Date] <= MAX(Datumstabelle[Date])
			    )
			)
			
			```
		lineageTag: 90beed7b-b983-4b78-b1ea-ac7f81a33564

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Kumuliertes Confirmed Orders' = ```
			
			CALCULATE(
			    [Confirmed Orders],
			    FILTER(
			        ALLSELECTED(Datumstabelle),
			        Datumstabelle[Date] <= MAX(Datumstabelle[Date])
			    )
			)
			
			```
		lineageTag: 5dbb79b3-af09-490e-aa58-8bbceb3a3f17

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Kumuliertes Unconfirmed Orders' = ```
			
			CALCULATE(
			    [Unconfirmed Orders],
			    FILTER(
			        ALLSELECTED(Datumstabelle),
			        Datumstabelle[Date] <= MAX(Datumstabelle[Date])
			    )
			)
			
			```
		lineageTag: ed416223-b8f0-4d6c-8de4-dada1930679c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum all' = [Net Value]+[Delivery Net Value]+sum('VMI-FC'[VMI-FC (EUR)])+[Confirmed Orders]+[Unconfirmed Orders]
		lineageTag: 679de4c7-5fef-47b2-974b-e2614b8581f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'All vs Budget' = ([Sum all]/[Budget revenues])-1
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7e0b207c-b3cf-4979-8d94-05f5535bcc47

	measure 'All vs Budget absolut' = [Sum all]-[Budget revenues]
		lineageTag: bab8af22-b2e0-4b6f-a5b7-4ebb74dfda62

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum all kumuliert' = [Kumulierter Net Value]+[Kumuliertes Confirmed Orders]+[Kumuliertes Delivery Net Value]+[Kumuliertes Unconfirmed Orders]+[Kumuliertes VMI-FC]
		lineageTag: adb797f5-380c-4fb4-80a3-05914162bf12

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'All vs Budget kumuliert' = ([Sum all kumuliert]/[Kumuliertes Budget])-1
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: c7615c42-32db-41d7-9595-9ed6c18b76b2

	measure 'Kumulierter Net Value PY' = CALCULATE([Kumulierter Net Value], SAMEPERIODLASTYEAR(Datumstabelle[Date].[Date]))
		lineageTag: 7d1690fd-6457-480e-80c4-17344e429ad7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Kumulierter Delivery Net Value PY' = CALCULATE([Kumuliertes Delivery Net Value], SAMEPERIODLASTYEAR(Datumstabelle[Date].[Date]))
		lineageTag: ea7ecec9-c6e6-40d4-9a94-c317979ce154

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Kumulierter VMI-FC PY' = CALCULATE([Kumuliertes VMI-FC], SAMEPERIODLASTYEAR(Datumstabelle[Date].[Date]))
		lineageTag: ea45168b-55d1-45ed-8926-a24c6853201a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Kumulierte Confirmed Orders PY' = CALCULATE([Kumuliertes Confirmed Orders], SAMEPERIODLASTYEAR(Datumstabelle[Date].[Date]))
		lineageTag: 83d2e2d1-45ae-4a9e-a3f3-e4cd316e9c1c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Kumulierte Unconfirmed Orders PY' = CALCULATE([Kumuliertes Unconfirmed Orders], SAMEPERIODLASTYEAR(Datumstabelle[Date].[Date]))
		lineageTag: b9eb66de-1af2-4ede-b2cf-c2beb859728c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Kumuliertes Budget PY' = CALCULATE([Kumuliertes Budget], SAMEPERIODLASTYEAR(Datumstabelle[Date].[Date]))
		lineageTag: ff37f7bb-19f2-4771-8535-0ca59a868828

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum all kumuliert PY' = CALCULATE([Sum all kumuliert], SAMEPERIODLASTYEAR(Datumstabelle[Date].[Date]))
		lineageTag: 8ab57192-ec6c-4f01-a43c-65e0134282e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum all kumuliert Vergleich' = ([Sum all kumuliert]/[Sum all kumuliert PY])-1
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7353c45f-d90d-4975-88bd-2e85e5da87a6

	column Value
		formatString: 0
		lineageTag: 154285dd-431d-4262-8f3c-f72f8c5ad3e2
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _Measures = calculated
		mode: import
		source = {1}

	annotation PBI_Id = 5cbf6b360a7e430bad6d1c0944d958eb

