table FACT_SALES_OPEN_ORDERS
	lineageTag: 8144ccaf-d4e2-4075-bde7-fca6c8233235

	measure 'Sum open Net Value' = Sum(FACT_SALES_OPEN_ORDERS[OPEN_NETVALUE_GC])
		formatString: #,0
		lineageTag: bc694258-e789-4ed3-94fc-07a31ad6d4a4

	column HUB_SALES_DOCUMENT_HKEY
		dataType: string
		lineageTag: a6d2c381-96d1-4c76-8656-e0240401fed8
		summarizeBy: none
		sourceColumn: HUB_SALES_DOCUMENT_HKEY

		annotation SummarizationSetBy = Automatic

	column HUB_SALES_DOCUMENT_LINEITEM_HKEY
		dataType: string
		lineageTag: 664765f4-4a91-422a-8d37-a4b205d02d61
		summarizeBy: none
		sourceColumn: HUB_SALES_DOCUMENT_LINEITEM_HKEY

		annotation SummarizationSetBy = Automatic

	column HUB_ACCOUNT_HKEY
		dataType: string
		lineageTag: b001bbe7-677d-4603-8a3f-964cfe7e7990
		summarizeBy: none
		sourceColumn: HUB_ACCOUNT_HKEY

		annotation SummarizationSetBy = Automatic

	column HUB_PRODUCT_HKEY
		dataType: string
		lineageTag: 9b03d993-3ebe-4772-ac09-c49e2ab653b0
		summarizeBy: none
		sourceColumn: HUB_PRODUCT_HKEY

		annotation SummarizationSetBy = Automatic

	column HUB_LOCATION_HKEY
		dataType: string
		lineageTag: ef0a853b-10c6-4532-a85b-07baa25fe375
		summarizeBy: none
		sourceColumn: HUB_LOCATION_HKEY

		annotation SummarizationSetBy = Automatic

	column CLIENT_CODE
		dataType: string
		lineageTag: 326a6a6b-ab82-419d-897a-7a45031c1d1e
		summarizeBy: none
		sourceColumn: CLIENT_CODE

		annotation SummarizationSetBy = Automatic

	column SALES_DOCUMENT_NR
		dataType: string
		lineageTag: d7977a34-58b1-4cb9-94b6-01909baeb50a
		summarizeBy: none
		sourceColumn: SALES_DOCUMENT_NR

		annotation SummarizationSetBy = Automatic

	column SALES_DOCUMENT_LINEITEM_NR
		dataType: string
		lineageTag: da07e9b4-0820-4b52-8d1a-d69171c75ee3
		summarizeBy: none
		sourceColumn: SALES_DOCUMENT_LINEITEM_NR

		annotation SummarizationSetBy = Automatic

	column DELIVERY_SCHEDULE_LINE_NR
		dataType: string
		lineageTag: 3f87b9c4-9f3f-4862-b2c6-30eae90793ff
		summarizeBy: none
		sourceColumn: DELIVERY_SCHEDULE_LINE_NR

		annotation SummarizationSetBy = Automatic

	column FLAG_INVOICED
		dataType: string
		lineageTag: ca3c548b-4c5e-48cf-84b8-30ea1f25211a
		summarizeBy: none
		sourceColumn: FLAG_INVOICED

		annotation SummarizationSetBy = Automatic

	column ACCOUNT_ID
		dataType: string
		lineageTag: decf520b-0556-467b-a192-fc90c6ef9ab1
		summarizeBy: none
		sourceColumn: ACCOUNT_ID

		annotation SummarizationSetBy = Automatic

	column PRODUCT_ID
		dataType: string
		lineageTag: 84f0de72-2415-435e-b4aa-a17488f852d2
		summarizeBy: none
		sourceColumn: PRODUCT_ID

		annotation SummarizationSetBy = Automatic

	column LOCATION_CODE
		dataType: string
		lineageTag: baba9b51-7eec-4712-8719-4c92dba4dd7a
		summarizeBy: none
		sourceColumn: LOCATION_CODE

		annotation SummarizationSetBy = Automatic

	column SALES_DOCUMENT_LINEITEM_CATEGORY
		dataType: string
		lineageTag: f217ad66-0b7c-4be5-9987-976090e87d91
		summarizeBy: none
		sourceColumn: SALES_DOCUMENT_LINEITEM_CATEGORY

		annotation SummarizationSetBy = Automatic

	column CURRENCY_CODE
		dataType: string
		lineageTag: 5ae162fe-9681-40c0-a11d-f4312bb74bbb
		summarizeBy: none
		sourceColumn: CURRENCY_CODE

		annotation SummarizationSetBy = Automatic

	column PRICING_UNIT
		dataType: string
		lineageTag: 969d420c-bbbb-44f4-a80b-139e0af98ad5
		summarizeBy: none
		sourceColumn: PRICING_UNIT

		annotation SummarizationSetBy = Automatic

	column BASE_UNIT_MEASURE
		dataType: string
		lineageTag: 45648967-16a6-46af-bce7-4b60fcdc634b
		summarizeBy: none
		sourceColumn: BASE_UNIT_MEASURE

		annotation SummarizationSetBy = Automatic

	column CONFIRMED_QUANTITY
		dataType: double
		lineageTag: 53093fe3-7dc4-4a7d-a8cf-ddc279e97c2e
		summarizeBy: sum
		sourceColumn: CONFIRMED_QUANTITY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FLAG_CONFIRMED_QTY
		dataType: int64
		formatString: 0
		lineageTag: a52d0798-8285-434c-b6ab-178099d3d00f
		summarizeBy: sum
		sourceColumn: FLAG_CONFIRMED_QTY

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column OPEN_ORDER_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: ad3477e3-3bc7-482c-8e3a-c5a5733bae50
		summarizeBy: none
		sourceColumn: OPEN_ORDER_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ACTUALCONFIRMEDDELIVERYDATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6522d1f7-6c10-4164-a9bc-d739f5b76195
		summarizeBy: none
		sourceColumn: ACTUALCONFIRMEDDELIVERYDATE

		variation Variation
			isDefault
			relationship: 9daab491-5565-4117-a394-1b49b2a9254c
			defaultHierarchy: LocalDateTable_8ebf0c0b-99be-4cbf-87d6-dcf61d1501c1.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ACTUALCONFIRMEDGOODSISSUEDATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1a26ff05-26aa-46c4-9dc9-93babdfc756f
		summarizeBy: none
		sourceColumn: ACTUALCONFIRMEDGOODSISSUEDATE

		variation Variation
			isDefault
			relationship: 36dab4fa-b2f9-42ff-855d-f7b0f7e8e0e2
			defaultHierarchy: LocalDateTable_5f02c680-ab31-408b-9e23-82520a1b616c.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CONFIRMED_QUANTITY_SUM_NEW
		dataType: string
		lineageTag: 2cd83fdc-0999-4ac1-a22a-a294f37bb687
		summarizeBy: none
		sourceColumn: CONFIRMED_QUANTITY_SUM_NEW

		annotation SummarizationSetBy = Automatic

	column IMPACT
		dataType: double
		lineageTag: 4c33ddfb-7568-4aea-ab52-55fbcef09e66
		summarizeBy: sum
		sourceColumn: IMPACT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OPEN_QUANTITY
		dataType: int64
		formatString: #,0
		lineageTag: bb78fe16-010b-44db-b54e-bf69791d2efd
		summarizeBy: sum
		sourceColumn: OPEN_QUANTITY

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column OPEN_NETVALUE_GC
		dataType: int64
		lineageTag: 1ed07f62-438e-4256-9c52-d0d2f4ba2961
		summarizeBy: sum
		sourceColumn: OPEN_NETVALUE_GC

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OMENG
		dataType: double
		lineageTag: 6b65ac4e-42a0-4ade-a705-e67ad90d5706
		summarizeBy: sum
		sourceColumn: OMENG

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUANTITY_AVAIL_CHECK
		dataType: double
		lineageTag: 7937225b-c703-451e-aeff-823b33e2b98d
		summarizeBy: sum
		sourceColumn: QUANTITY_AVAIL_CHECK

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SITECODE
		dataType: string
		lineageTag: a3e1e837-5da6-4aaa-a6cf-c7e24c1636db
		summarizeBy: none
		sourceColumn: SITECODE

		annotation SummarizationSetBy = Automatic

	column 'Legal Entity'
		dataType: string
		lineageTag: 7c2c5b18-7f3c-4b8d-9b5e-1bb5d2830411
		summarizeBy: none
		sourceColumn: Legal Entity

		annotation SummarizationSetBy = Automatic

	column blank = blank()
		formatString: 0
		lineageTag: 4846e921-380c-4d5f-9381-feed4a946a92
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Confirmed Flag Text' = if(FACT_SALES_OPEN_ORDERS[FLAG_CONFIRMED_QTY]=0, "Unconfirmed", "Confirmed")
		lineageTag: 0c012422-02ec-46e9-b9dd-3e8f456cd3d8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FACT_SALES_OPEN_ORDERS = m
		mode: import
		source =
				let
				    Quelle = Snowflake.Databases(SF_SERVER,SF_WAREHOUSE),
				    SF_DWH_DATAVAULT_Database = Quelle{[Name="SF_DWH_DATAVAULT",Kind="Database"]}[Data],
				    DWH_MART_SALES_Schema = SF_DWH_DATAVAULT_Database{[Name="DWH_MART_SALES",Kind="Schema"]}[Data],
				    FACT_SALES_OPEN_ORDERS_View = DWH_MART_SALES_Schema{[Name="FACT_SALES_OPEN_ORDERS",Kind="View"]}[Data],
				    #"Hinzugefügte benutzerdefinierte Spalte" = Table.AddColumn(FACT_SALES_OPEN_ORDERS_View, "SITECODE", each if [LOCATION_CODE]=0050 then "TIM" else if [LOCATION_CODE]=0091 then "AIP" else if [LOCATION_CODE]=1000 then "WOR" else if [LOCATION_CODE]=2100 then "KIR" else if [LOCATION_CODE]=2101 then "BAA" else if [LOCATION_CODE]=2104 then "COR" else if [LOCATION_CODE]=3000 then "MST" else if [LOCATION_CODE]=4400 then "RGB" else if [LOCATION_CODE]=4499 then "RGB" else if [LOCATION_CODE]=6200 then "LAT" else if [LOCATION_CODE]=6500 then "KIL" else if [LOCATION_CODE]=6650 then "CAR" else if [LOCATION_CODE]=7010 then "MRB" else [LOCATION_CODE]),
				    #"Hinzugefügte benutzerdefinierte Spalte1" = Table.AddColumn(#"Hinzugefügte benutzerdefinierte Spalte", "Legal Entity", each if [LOCATION_CODE]= "0050" then "Dragenopharm Apotheker Püschl GmbH" else if [LOCATION_CODE]="2100" then "SWISS CAPS AG" else if [LOCATION_CODE]="2101" then "SWISS CAPS AG" else if [LOCATION_CODE]="2104" then "SWISS CAPS AG" else if [LOCATION_CODE]="2400" then "SWISS CAPS AG" else if [LOCATION_CODE]="2404" then "SWISS CAPS AG" else if [LOCATION_CODE]="3000" then "Haupt Pharma Münster GmbH" else if [LOCATION_CODE]="4400" then "Haupt Pharma Amareg GmbH" else if [LOCATION_CODE]=4499 then "Haupt Pharma Amareg GmbH" else if [LOCATION_CODE]="6200" then "Haupt Pharma Latina S.r.l." else if [LOCATION_CODE]="6500" then "Temmler Ireland Ltd." else if [LOCATION_CODE]="7010" then "Temmler Pharma GmbH"  else [LOCATION_CODE])
				in
				    #"Hinzugefügte benutzerdefinierte Spalte1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

